package com.abhijith.lms.model.role;
//Generated 2 Sep, 2021 1:29:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.abhijith.lms.model.role_access.RoleAccess;

/**
* Roles generated by hbm2java
*/
@Entity
@Table(name="roles"
 ,catalog="libsys"
)
public class Roles  implements java.io.Serializable {


  private Integer roleId;
  private String roleName;
  private String status;
  private Set<RoleAccess> roleAccesses = new HashSet<RoleAccess>(0);

 public Roles() {
 }

	
 public Roles(String roleName, String status) {
     this.roleName = roleName;
     this.status = status;
 }
 public Roles(String roleName, String status, Set<RoleAccess> roleAccesses) {
    this.roleName = roleName;
    this.status = status;
    this.roleAccesses = roleAccesses;
 }

  @Id @GeneratedValue(strategy=IDENTITY)

 
 @Column(name="role_id", unique=true, nullable=false)
 public Integer getRoleId() {
     return this.roleId;
 }
 
 public void setRoleId(Integer roleId) {
     this.roleId = roleId;
 }

 
 @Column(name="role_name", nullable=false, length=45)
 public String getRoleName() {
     return this.roleName;
 }
 
 public void setRoleName(String roleName) {
     this.roleName = roleName;
 }

 
 @Column(name="status", nullable=false, length=10)
 public String getStatus() {
     return this.status;
 }
 
 public void setStatus(String status) {
     this.status = status;
 }

@OneToMany(fetch=FetchType.LAZY, mappedBy="roles")
 public Set<RoleAccess> getRoleAccesses() {
     return this.roleAccesses;
 }
 
 public void setRoleAccesses(Set<RoleAccess> roleAccesses) {
     this.roleAccesses = roleAccesses;
 }




}


