package com.abhijith.lms.model.book;
//Generated 2 Sep, 2021 1:29:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.abhijith.lms.model.user_book.UserBookRel;

/**
* Book generated by hbm2java
*/
@Entity
@Table(name="book"
 ,catalog="libsys"
 , uniqueConstraints = @UniqueConstraint(columnNames="isbn") 
)
public class Book  implements java.io.Serializable {


  private Integer bookId;
  private String isbn;
  private String name;
  private String author;
  private String status;
  private Set<UserBookRel> userBookRels = new HashSet<UserBookRel>(0);

 public Book() {
 }

	
 public Book(String isbn, String name, String author, String status) {
     this.isbn = isbn;
     this.name = name;
     this.author = author;
     this.status = status;
 }
 public Book(String isbn, String name, String author, String status, Set<UserBookRel> userBookRels) {
    this.isbn = isbn;
    this.name = name;
    this.author = author;
    this.status = status;
    this.userBookRels = userBookRels;
 }

  @Id @GeneratedValue(strategy=IDENTITY)

 
 @Column(name="book_id", unique=true, nullable=false)
 public Integer getBookId() {
     return this.bookId;
 }
 
 public void setBookId(Integer bookId) {
     this.bookId = bookId;
 }

 
 @Column(name="isbn", unique=true, nullable=false, length=100)
 public String getIsbn() {
     return this.isbn;
 }
 
 public void setIsbn(String isbn) {
     this.isbn = isbn;
 }

 
 @Column(name="name", nullable=false, length=200)
 public String getName() {
     return this.name;
 }
 
 public void setName(String name) {
     this.name = name;
 }

 
 @Column(name="author", nullable=false, length=100)
 public String getAuthor() {
     return this.author;
 }
 
 public void setAuthor(String author) {
     this.author = author;
 }

 
 @Column(name="status", nullable=false, length=10)
 public String getStatus() {
     return this.status;
 }
 
 public void setStatus(String status) {
     this.status = status;
 }

@OneToMany(fetch=FetchType.LAZY, mappedBy="book")
 public Set<UserBookRel> getUserBookRels() {
     return this.userBookRels;
 }
 
 public void setUserBookRels(Set<UserBookRel> userBookRels) {
     this.userBookRels = userBookRels;
 }




}
