package com.abhijith.lms.model.user;
//Generated 2 Sep, 2021 1:29:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.abhijith.lms.model.user_book.UserBookRel;

/**
* User generated by hbm2java
*/
@Entity
@Table(name="user"
 ,catalog="libsys"
)
public class User  implements java.io.Serializable {


  private Integer userId;
  private String nameFirst;
  private String nameLast;
  private String status;
  private int roleId;
  private Set<UserBookRel> userBookRels = new HashSet<UserBookRel>(0);

 public User() {
 }

	
 public User(String nameFirst, String nameLast, String status, int roleId) {
     this.nameFirst = nameFirst;
     this.nameLast = nameLast;
     this.status = status;
     this.roleId = roleId;
 }
 public User(String nameFirst, String nameLast, String status, int roleId, Set<UserBookRel> userBookRels) {
    this.nameFirst = nameFirst;
    this.nameLast = nameLast;
    this.status = status;
    this.roleId = roleId;
    this.userBookRels = userBookRels;
 }

  @Id @GeneratedValue(strategy=IDENTITY)

 
 @Column(name="user_id", unique=true, nullable=false)
 public Integer getUserId() {
     return this.userId;
 }
 
 public void setUserId(Integer userId) {
     this.userId = userId;
 }

 
 @Column(name="name_first", nullable=false, length=100)
 public String getNameFirst() {
     return this.nameFirst;
 }
 
 public void setNameFirst(String nameFirst) {
     this.nameFirst = nameFirst;
 }

 
 @Column(name="name_last", nullable=false, length=100)
 public String getNameLast() {
     return this.nameLast;
 }
 
 public void setNameLast(String nameLast) {
     this.nameLast = nameLast;
 }

 
 @Column(name="status", nullable=false, length=10)
 public String getStatus() {
     return this.status;
 }
 
 public void setStatus(String status) {
     this.status = status;
 }

 
 @Column(name="role_id", nullable=false)
 public int getRoleId() {
     return this.roleId;
 }
 
 public void setRoleId(int roleId) {
     this.roleId = roleId;
 }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
 public Set<UserBookRel> getUserBookRels() {
     return this.userBookRels;
 }
 
 public void setUserBookRels(Set<UserBookRel> userBookRels) {
     this.userBookRels = userBookRels;
 }




}
