package com.abhijith.lms.model.user_book;
//Generated 2 Sep, 2021 1:29:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.abhijith.lms.model.book.Book;
import com.abhijith.lms.model.user.User;

/**
* UserBookRel generated by hbm2java
*/
@Entity
@Table(name="user_book_rel"
 ,catalog="libsys"
)
public class UserBookRel  implements java.io.Serializable {


  private Integer userBookId;
  private Book book;
  private User user;
  private String status;
  private Date requestedDate;
  private Date issuedDate;
  private Date returnDate;

 public UserBookRel() {
 }

	
 public UserBookRel(Book book, User user, String status) {
     this.book = book;
     this.user = user;
     this.status = status;
 }
 public UserBookRel(Book book, User user, String status, Date requestedDate, Date issuedDate, Date returnDate) {
    this.book = book;
    this.user = user;
    this.status = status;
    this.requestedDate = requestedDate;
    this.issuedDate = issuedDate;
    this.returnDate = returnDate;
 }

  @Id @GeneratedValue(strategy=IDENTITY)

 
 @Column(name="user_book_id", unique=true, nullable=false)
 public Integer getUserBookId() {
     return this.userBookId;
 }
 
 public void setUserBookId(Integer userBookId) {
     this.userBookId = userBookId;
 }

@ManyToOne(fetch=FetchType.LAZY)
 @JoinColumn(name="book_id", nullable=false)
 public Book getBook() {
     return this.book;
 }
 
 public void setBook(Book book) {
     this.book = book;
 }

@ManyToOne(fetch=FetchType.LAZY)
 @JoinColumn(name="user_id", nullable=false)
 public User getUser() {
     return this.user;
 }
 
 public void setUser(User user) {
     this.user = user;
 }

 
 @Column(name="status", nullable=false, length=10)
 public String getStatus() {
     return this.status;
 }
 
 public void setStatus(String status) {
     this.status = status;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name="requested_date", length=19)
 public Date getRequestedDate() {
     return this.requestedDate;
 }
 
 public void setRequestedDate(Date requestedDate) {
     this.requestedDate = requestedDate;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name="issued_date", length=19)
 public Date getIssuedDate() {
     return this.issuedDate;
 }
 
 public void setIssuedDate(Date issuedDate) {
     this.issuedDate = issuedDate;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name="return_date", length=19)
 public Date getReturnDate() {
     return this.returnDate;
 }
 
 public void setReturnDate(Date returnDate) {
     this.returnDate = returnDate;
 }




}